### ISSUE TITLE
ByBit futures

### ISSUE THREAD

**Issue by Pusherman2** [WiktorBK/ByBitBot#1]
Hi there, 

Interesting project, can this also work for derivatives/ByBit Futures contracts?

Also might want to look into using Telegram for notifications, much more convenient and very easy to implement in Python :)

**Comment by WiktorBK** [comment]
Hi,
thanks for this comment! 
BybitBot only works for USDT Perpetual contracts.
I will consider implementing Telegram to this project in the near future :)
